[package]
name = "remotia-buffer-utils"
version = "0.1.0"
edition = "2021"

[dependencies.tokio]
version = "1.28.2"
features = ["rt", "sync", "time"]

[dependencies]
remotia-core = { path = "../remotia-core" }

log = "0.4.14"

async-trait = "0.1.68"
bytes = "1.4.0"
